### ISSUE TITLE
Which raw-source PUF should we synthesize?

### ISSUE THREAD

**Issue by donboyd5** [donboyd5/synpuf#13]
Just want to make sure we agree on the right starting place. I think it should be the raw 2011 PUF as obtained from SOI - the highlighted file in the snapshot below from dropbox as seen on my machine.

![image](https://user-images.githubusercontent.com/6538392/49688174-0e08b180-fadc-11e8-886f-876f3838a497.png)

@MaxGhenis, @andersonfrailey, @feenberg, do you agree?

**Comment by andersonfrailey** [comment]
@donboyd5 yes I agree with you.
