### ISSUE TITLE
Uploaded pufvars.csv

### ISSUE THREAD

**Issue by donboyd5** [donboyd5/synpuf#14]
This has probably been done 100 times, but maybe this will save someone else from creating version 101.

I created pufvars.csv with puf2011 variable names and the SOI descriptions, copied from the 2011 public use booklet. The file is in the data directory of synpuf.

If there is a better way to do things like this via github, please let me know (@MaxGhenis, @andersonfrailey).

**Comment by MaxGhenis** [comment]
This is at https://github.com/donboyd5/synpuf/blob/master/data/pufvars.csv

I also put it in Google Sheets [here](https://docs.google.com/spreadsheets/d/12UfjTjAAIZtNmn0Klytx742j09qcgw8kYxVhHBaZ1zc).
