### ISSUE TITLE
Add collaborators

### ISSUE THREAD

**Issue by MaxGhenis** [donboyd5/synpuf#18]
@donboyd5 could you add me and others as collaborators? This should do it: https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/

**Comment by donboyd5** [comment]
Hi Max, I tried (but may not have succeeded) to do that before (screenshot).

Here is the link it gives me when I ask to copy link:
https://github.com/donboyd5/synpuf/invitations
It doesn't seem to be personalized to you, as I would expect.

If that doesn't work, can you let me know?

Thanks.

Don



[image: image.png]

**Comment by MaxGhenis** [comment]
The screenshot didn't come through, but actually apparently I am a collaborator based on it being in the left panel of my dashboard (I was expecting something visual on the repo site). Never mind!

**Comment by MaxGhenis** [comment]
I accepted the invitation via that link. Hopefully it only works for accounts you've authorized.

**Comment by MaxGhenis** [comment]
@feenberg could you accept the [invitation](https://github.com/donboyd5/synpuf/invitations) as well so tags auto-complete for you? I'd also like to assign issues to contributors, and I'm only able to assign to Don, Anderson, Matt, and myself.

**Comment by feenberg** [comment]
done
